// <auto-generated/>
using System;
using System.Collections.Generic;
using BinaryExprOpcode = Microsoft.Dafny.BinaryExpr.Opcode;

namespace Microsoft.Dafny
{
    partial class SyntaxDeserializer
    {
        public TokenRangeOrigin ReadTokenRangeOrigin()
        {
            var parameter0 = ReadToken();
            var parameter1 = ReadToken();
            return new TokenRangeOrigin(parameter0, parameter1);
        }

        public TokenRangeOrigin ReadTokenRangeOriginOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadTokenRangeOrigin();
        }

        public SourceOrigin ReadSourceOrigin()
        {
            var parameter0 = ReadTokenRange();
            var parameter1 = ReadTokenRangeOption();
            return new SourceOrigin(parameter0, parameter1);
        }

        public SourceOrigin ReadSourceOriginOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadSourceOrigin();
        }

        public TokenRange ReadTokenRange()
        {
            var parameter0 = ReadToken();
            var parameter1 = ReadTokenOption();
            return new TokenRange(parameter0, parameter1);
        }

        public TokenRange ReadTokenRangeOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadTokenRange();
        }

        public UserDefinedType ReadUserDefinedType()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            return new UserDefinedType(parameter0, parameter1);
        }

        public UserDefinedType ReadUserDefinedTypeOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadUserDefinedType();
        }

        public LetExpr ReadLetExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadList<CasePattern<BoundVar>>(() => ReadCasePattern<BoundVar>());
            var parameter2 = ReadList<Expression>(() => ReadAbstract<Expression>());
            var parameter3 = ReadAbstract<Expression>();
            var parameter4 = ReadBoolean();
            var parameter5 = ReadAttributesOption();
            return new LetExpr(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5);
        }

        public LetExpr ReadLetExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadLetExpr();
        }

        public Attributes ReadAttributes()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadString();
            var parameter2 = ReadList<Expression>(() => ReadAbstract<Expression>());
            var parameter3 = ReadAttributesOption();
            return new Attributes(parameter0, parameter1, parameter2, parameter3);
        }

        public Attributes ReadAttributesOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadAttributes();
        }

        public IdentifierExpr ReadIdentifierExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadString();
            return new IdentifierExpr(parameter0, parameter1);
        }

        public IdentifierExpr ReadIdentifierExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadIdentifierExpr();
        }

        public AutoGhostIdentifierExpr ReadAutoGhostIdentifierExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadString();
            return new AutoGhostIdentifierExpr(parameter0, parameter1);
        }

        public AutoGhostIdentifierExpr ReadAutoGhostIdentifierExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadAutoGhostIdentifierExpr();
        }

        public ConversionExpr ReadConversionExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            var parameter2 = ReadAbstract<Type>();
            var parameter3 = ReadString();
            return new ConversionExpr(parameter0, parameter1, parameter2, parameter3);
        }

        public ConversionExpr ReadConversionExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadConversionExpr();
        }

        public UnaryOpExpr ReadUnaryOpExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter2 = ReadAbstract<Expression>();
            var parameter1 = ReadUnaryOpExprOpcode();
            return new UnaryOpExpr(parameter0, parameter1, parameter2);
        }

        public UnaryOpExpr ReadUnaryOpExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadUnaryOpExpr();
        }

        private UnaryOpExpr.Opcode ReadUnaryOpExprOpcode()
        {
            int ordinal = ReadInt32();
            return (UnaryOpExpr.Opcode)ordinal;
        }

        public FreshExpr ReadFreshExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            var parameter2 = ReadStringOption();
            return new FreshExpr(parameter0, parameter1, parameter2);
        }

        public FreshExpr ReadFreshExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadFreshExpr();
        }

        public BinaryExpr ReadBinaryExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadBinaryExprOpcode();
            var parameter2 = ReadAbstract<Expression>();
            var parameter3 = ReadAbstract<Expression>();
            return new BinaryExpr(parameter0, parameter1, parameter2, parameter3);
        }

        public BinaryExpr ReadBinaryExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadBinaryExpr();
        }

        private BinaryExpr.Opcode ReadBinaryExprOpcode()
        {
            int ordinal = ReadInt32();
            return (BinaryExpr.Opcode)ordinal;
        }

        public LiteralExpr ReadLiteralExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstractOption<Object>();
            return new LiteralExpr(parameter0, parameter1);
        }

        public LiteralExpr ReadLiteralExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadLiteralExpr();
        }

        public StringLiteralExpr ReadStringLiteralExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Object>();
            var parameter2 = ReadBoolean();
            return new StringLiteralExpr(parameter0, parameter1, parameter2);
        }

        public StringLiteralExpr ReadStringLiteralExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadStringLiteralExpr();
        }

        public CharLiteralExpr ReadCharLiteralExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Object>();
            return new CharLiteralExpr(parameter0, parameter1);
        }

        public CharLiteralExpr ReadCharLiteralExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadCharLiteralExpr();
        }

        public UnchangedExpr ReadUnchangedExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadList<FrameExpression>(() => ReadFrameExpression());
            var parameter2 = ReadStringOption();
            return new UnchangedExpr(parameter0, parameter1, parameter2);
        }

        public UnchangedExpr ReadUnchangedExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadUnchangedExpr();
        }

        public FrameExpression ReadFrameExpression()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            var parameter2 = ReadStringOption();
            return new FrameExpression(parameter0, parameter1, parameter2);
        }

        public FrameExpression ReadFrameExpressionOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadFrameExpression();
        }

        public OldExpr ReadOldExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            var parameter2 = ReadStringOption();
            return new OldExpr(parameter0, parameter1, parameter2);
        }

        public OldExpr ReadOldExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadOldExpr();
        }

        public DatatypeValue ReadDatatypeValue()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadString();
            var parameter2 = ReadString();
            var parameter3 = ReadActualBindings();
            return new DatatypeValue(parameter0, parameter1, parameter2, parameter3);
        }

        public DatatypeValue ReadDatatypeValueOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadDatatypeValue();
        }

        public ModuleQualifiedId ReadModuleQualifiedId()
        {
            var parameter0 = ReadList<Name>(() => ReadName());
            return new ModuleQualifiedId(parameter0);
        }

        public ModuleQualifiedId ReadModuleQualifiedIdOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadModuleQualifiedId();
        }

        public Name ReadName()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadString();
            return new Name(parameter0, parameter1);
        }

        public Name ReadNameOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadName();
        }

        public ActualBinding ReadActualBinding()
        {
            var parameter0 = ReadAbstractOption<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            var parameter2 = ReadBoolean();
            return new ActualBinding(parameter0, parameter1, parameter2);
        }

        public ActualBinding ReadActualBindingOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadActualBinding();
        }

        public ActualBindings ReadActualBindings()
        {
            var parameter0 = ReadList<ActualBinding>(() => ReadActualBinding());
            return new ActualBindings(parameter0);
        }

        public ActualBindings ReadActualBindingsOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadActualBindings();
        }

        public TernaryExpr ReadTernaryExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadTernaryExprOpcode();
            var parameter2 = ReadAbstract<Expression>();
            var parameter3 = ReadAbstract<Expression>();
            var parameter4 = ReadAbstract<Expression>();
            return new TernaryExpr(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public TernaryExpr ReadTernaryExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadTernaryExpr();
        }

        private TernaryExpr.Opcode ReadTernaryExprOpcode()
        {
            int ordinal = ReadInt32();
            return (TernaryExpr.Opcode)ordinal;
        }

        public NestedMatchExpr ReadNestedMatchExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            var parameter2 = ReadList<NestedMatchCaseExpr>(() => ReadNestedMatchCaseExpr());
            var parameter3 = ReadBoolean();
            var parameter4 = ReadAttributesOption();
            return new NestedMatchExpr(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public NestedMatchExpr ReadNestedMatchExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadNestedMatchExpr();
        }

        public LitPattern ReadLitPattern()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter2 = ReadBoolean();
            var parameter1 = ReadAbstract<Expression>();
            return new LitPattern(parameter0, parameter1, parameter2);
        }

        public LitPattern ReadLitPatternOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadLitPattern();
        }

        public IdPattern ReadIdPattern()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter4 = ReadBoolean();
            var parameter1 = ReadString();
            var parameter2 = ReadAbstractOption<Type>();
            var parameter3 = ReadListOption<ExtendedPattern>(() => ReadAbstract<ExtendedPattern>());
            var parameter5 = ReadBoolean();
            return new IdPattern(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5);
        }

        public IdPattern ReadIdPatternOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadIdPattern();
        }

        public DisjunctivePattern ReadDisjunctivePattern()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter2 = ReadBoolean();
            var parameter1 = ReadList<ExtendedPattern>(() => ReadAbstract<ExtendedPattern>());
            return new DisjunctivePattern(parameter0, parameter1, parameter2);
        }

        public DisjunctivePattern ReadDisjunctivePatternOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadDisjunctivePattern();
        }

        public NestedMatchCaseStmt ReadNestedMatchCaseStmt()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<ExtendedPattern>();
            var parameter2 = ReadList<Statement>(() => ReadAbstract<Statement>());
            var parameter3 = ReadAttributesOption();
            return new NestedMatchCaseStmt(parameter0, parameter1, parameter2, parameter3);
        }

        public NestedMatchCaseStmt ReadNestedMatchCaseStmtOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadNestedMatchCaseStmt();
        }

        public ExpectStmt ReadExpectStmt()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter3 = ReadAttributesOption();
            var parameter1 = ReadAbstract<Expression>();
            var parameter2 = ReadAbstractOption<Expression>();
            return new ExpectStmt(parameter0, parameter1, parameter2, parameter3);
        }

        public ExpectStmt ReadExpectStmtOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadExpectStmt();
        }

        public AssertStmt ReadAssertStmt()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter3 = ReadAttributesOption();
            var parameter1 = ReadAbstract<Expression>();
            var parameter2 = ReadAssertLabelOption();
            return new AssertStmt(parameter0, parameter1, parameter2, parameter3);
        }

        public AssertStmt ReadAssertStmtOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadAssertStmt();
        }

        public Label ReadLabel()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadString();
            return new Label(parameter0, parameter1);
        }

        public Label ReadLabelOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadLabel();
        }

        public AssertLabel ReadAssertLabel()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadString();
            return new AssertLabel(parameter0, parameter1);
        }

        public AssertLabel ReadAssertLabelOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadAssertLabel();
        }

        public AllocateClass ReadAllocateClass()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter3 = ReadAttributesOption();
            var parameter1 = ReadAbstract<Type>();
            var parameter2 = ReadActualBindingsOption();
            return new AllocateClass(parameter0, parameter1, parameter2, parameter3);
        }

        public AllocateClass ReadAllocateClassOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadAllocateClass();
        }

        public AllocateArray ReadAllocateArray()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter4 = ReadAttributesOption();
            var parameter1 = ReadAbstractOption<Type>();
            var parameter2 = ReadList<Expression>(() => ReadAbstract<Expression>());
            var parameter3 = ReadAbstractOption<Expression>();
            return new AllocateArray(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public AllocateArray ReadAllocateArrayOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadAllocateArray();
        }

        public ExprRhs ReadExprRhs()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter2 = ReadAttributesOption();
            var parameter1 = ReadAbstract<Expression>();
            return new ExprRhs(parameter0, parameter1, parameter2);
        }

        public ExprRhs ReadExprRhsOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadExprRhs();
        }

        public ReturnStmt ReadReturnStmt()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter2 = ReadAttributesOption();
            var parameter1 = ReadListOption<AssignmentRhs>(() => ReadAbstract<AssignmentRhs>());
            return new ReturnStmt(parameter0, parameter1, parameter2);
        }

        public ReturnStmt ReadReturnStmtOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadReturnStmt();
        }

        public PrintStmt ReadPrintStmt()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter2 = ReadAttributesOption();
            var parameter1 = ReadList<Expression>(() => ReadAbstract<Expression>());
            return new PrintStmt(parameter0, parameter1, parameter2);
        }

        public PrintStmt ReadPrintStmtOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadPrintStmt();
        }

        public LabeledStatement ReadLabeledStatement()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter2 = ReadAttributesOption();
            var parameter1 = ReadList<Label>(() => ReadLabel());
            return new LabeledStatement(parameter0, parameter1, parameter2);
        }

        public LabeledStatement ReadLabeledStatementOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadLabeledStatement();
        }

        public AttributedExpression ReadAttributedExpression()
        {
            var parameter0 = ReadAbstract<Expression>();
            var parameter1 = ReadAssertLabelOption();
            var parameter2 = ReadAttributesOption();
            return new AttributedExpression(parameter0, parameter1, parameter2);
        }

        public AttributedExpression ReadAttributedExpressionOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadAttributedExpression();
        }

        public DividedBlockStmt ReadDividedBlockStmt()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter5 = ReadAttributesOption();
            var parameter4 = ReadList<Label>(() => ReadLabel());
            var parameter1 = ReadList<Statement>(() => ReadAbstract<Statement>());
            var parameter2 = ReadAbstractOption<IOrigin>();
            var parameter3 = ReadList<Statement>(() => ReadAbstract<Statement>());
            return new DividedBlockStmt(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5);
        }

        public DividedBlockStmt ReadDividedBlockStmtOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadDividedBlockStmt();
        }

        public BlockStmt ReadBlockStmt()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter3 = ReadAttributesOption();
            var parameter2 = ReadList<Label>(() => ReadLabel());
            var parameter1 = ReadList<Statement>(() => ReadAbstract<Statement>());
            return new BlockStmt(parameter0, parameter1, parameter2, parameter3);
        }

        public BlockStmt ReadBlockStmtOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadBlockStmt();
        }

        public OpaqueBlock ReadOpaqueBlock()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter5 = ReadAttributesOption();
            var parameter4 = ReadList<Label>(() => ReadLabel());
            var parameter1 = ReadList<Statement>(() => ReadAbstract<Statement>());
            var parameter2 = ReadList<AttributedExpression>(() => ReadAttributedExpression());
            var parameter3 = ReadSpecification<FrameExpression>();
            return new OpaqueBlock(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5);
        }

        public OpaqueBlock ReadOpaqueBlockOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadOpaqueBlock();
        }

        public WhileStmt ReadWhileStmt()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter7 = ReadAttributesOption();
            var parameter6 = ReadList<Label>(() => ReadLabel());
            var parameter2 = ReadList<AttributedExpression>(() => ReadAttributedExpression());
            var parameter3 = ReadSpecification<Expression>();
            var parameter4 = ReadSpecification<FrameExpression>();
            var parameter5 = ReadBlockStmt();
            var parameter1 = ReadAbstract<Expression>();
            return new WhileStmt(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, parameter7);
        }

        public WhileStmt ReadWhileStmtOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadWhileStmt();
        }

        public IfStmt ReadIfStmt()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter6 = ReadAttributesOption();
            var parameter5 = ReadList<Label>(() => ReadLabel());
            var parameter1 = ReadBoolean();
            var parameter2 = ReadAbstractOption<Expression>();
            var parameter3 = ReadBlockStmt();
            var parameter4 = ReadAbstractOption<Statement>();
            return new IfStmt(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6);
        }

        public IfStmt ReadIfStmtOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadIfStmt();
        }

        public BreakOrContinueStmt ReadBreakOrContinueStmt()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter4 = ReadAttributesOption();
            var parameter1 = ReadNameOption();
            var parameter2 = ReadInt32();
            var parameter3 = ReadBoolean();
            return new BreakOrContinueStmt(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public BreakOrContinueStmt ReadBreakOrContinueStmtOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadBreakOrContinueStmt();
        }

        public VarDeclStmt ReadVarDeclStmt()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter3 = ReadAttributesOption();
            var parameter1 = ReadList<LocalVariable>(() => ReadLocalVariable());
            var parameter2 = ReadAbstractOption<ConcreteAssignStatement>();
            return new VarDeclStmt(parameter0, parameter1, parameter2, parameter3);
        }

        public VarDeclStmt ReadVarDeclStmtOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadVarDeclStmt();
        }

        public AssignStatement ReadAssignStatement()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter4 = ReadAttributesOption();
            var parameter1 = ReadList<Expression>(() => ReadAbstract<Expression>());
            var parameter2 = ReadList<AssignmentRhs>(() => ReadAbstract<AssignmentRhs>());
            var parameter3 = ReadBoolean();
            return new AssignStatement(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public AssignStatement ReadAssignStatementOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadAssignStatement();
        }

        public LocalVariable ReadLocalVariable()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadString();
            var parameter2 = ReadAbstractOption<Type>();
            var parameter3 = ReadBoolean();
            return new LocalVariable(parameter0, parameter1, parameter2, parameter3);
        }

        public LocalVariable ReadLocalVariableOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadLocalVariable();
        }

        public NestedMatchStmt ReadNestedMatchStmt()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter4 = ReadAttributesOption();
            var parameter1 = ReadAbstract<Expression>();
            var parameter2 = ReadList<NestedMatchCaseStmt>(() => ReadNestedMatchCaseStmt());
            var parameter3 = ReadBoolean();
            return new NestedMatchStmt(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public NestedMatchStmt ReadNestedMatchStmtOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadNestedMatchStmt();
        }

        public NestedMatchCaseExpr ReadNestedMatchCaseExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<ExtendedPattern>();
            var parameter2 = ReadAbstract<Expression>();
            var parameter3 = ReadAttributesOption();
            return new NestedMatchCaseExpr(parameter0, parameter1, parameter2, parameter3);
        }

        public NestedMatchCaseExpr ReadNestedMatchCaseExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadNestedMatchCaseExpr();
        }

        public ITEExpr ReadITEExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadBoolean();
            var parameter2 = ReadAbstract<Expression>();
            var parameter3 = ReadAbstract<Expression>();
            var parameter4 = ReadAbstract<Expression>();
            return new ITEExpr(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public ITEExpr ReadITEExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadITEExpr();
        }

        public LetOrFailExpr ReadLetOrFailExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadCasePatternOption<BoundVar>();
            var parameter2 = ReadAbstract<Expression>();
            var parameter3 = ReadAbstract<Expression>();
            return new LetOrFailExpr(parameter0, parameter1, parameter2, parameter3);
        }

        public LetOrFailExpr ReadLetOrFailExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadLetOrFailExpr();
        }

        public Formal ReadFormal()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter2 = ReadAbstractOption<Type>();
            var parameter4 = ReadBoolean();
            var parameter3 = ReadBoolean();
            var parameter5 = ReadAbstractOption<Expression>();
            var parameter6 = ReadAttributesOption();
            var parameter7 = ReadBoolean();
            var parameter8 = ReadBoolean();
            var parameter9 = ReadBoolean();
            var parameter10 = ReadStringOption();
            return new Formal(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, parameter7, parameter8, parameter9, parameter10);
        }

        public Formal ReadFormalOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadFormal();
        }

        public BoundVar ReadBoundVar()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter2 = ReadAbstractOption<Type>();
            var parameter3 = ReadBoolean();
            return new BoundVar(parameter0, parameter1, parameter2, parameter3);
        }

        public BoundVar ReadBoundVarOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadBoundVar();
        }

        public QuantifiedVar ReadQuantifiedVar()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter2 = ReadAbstractOption<Type>();
            var parameter3 = ReadAbstractOption<Expression>();
            var parameter4 = ReadAbstractOption<Expression>();
            return new QuantifiedVar(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public QuantifiedVar ReadQuantifiedVarOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadQuantifiedVar();
        }

        public ParensExpression ReadParensExpression()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            return new ParensExpression(parameter0, parameter1);
        }

        public ParensExpression ReadParensExpressionOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadParensExpression();
        }

        public ChainingExpression ReadChainingExpression()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadList<Expression>(() => ReadAbstract<Expression>());
            var parameter2 = ReadList<BinaryExprOpcode>(() => ReadBinaryExprOpcode());
            var parameter3 = ReadList<IOrigin>(() => ReadAbstract<IOrigin>());
            var parameter4 = ReadList<Expression>(() => ReadAbstractOption<Expression>());
            return new ChainingExpression(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public ChainingExpression ReadChainingExpressionOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadChainingExpression();
        }

        public NegationExpression ReadNegationExpression()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            return new NegationExpression(parameter0, parameter1);
        }

        public NegationExpression ReadNegationExpressionOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadNegationExpression();
        }

        public ExprDotName ReadExprDotName()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            var parameter2 = ReadName();
            var parameter3 = ReadListOption<Type>(() => ReadAbstract<Type>());
            return new ExprDotName(parameter0, parameter1, parameter2, parameter3);
        }

        public ExprDotName ReadExprDotNameOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadExprDotName();
        }

        public ApplySuffix ReadApplySuffix()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter2 = ReadAbstract<Expression>();
            var parameter1 = ReadAbstractOption<IOrigin>();
            var parameter3 = ReadActualBindings();
            var parameter4 = ReadTokenOption();
            return new ApplySuffix(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public ApplySuffix ReadApplySuffixOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadApplySuffix();
        }

        public NameSegment ReadNameSegment()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadString();
            var parameter2 = ReadListOption<Type>(() => ReadAbstract<Type>());
            return new NameSegment(parameter0, parameter1, parameter2);
        }

        public NameSegment ReadNameSegmentOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadNameSegment();
        }

        public SetComprehension ReadSetComprehension()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter2 = ReadList<BoundVar>(() => ReadBoundVar());
            var parameter3 = ReadAbstract<Expression>();
            var parameter4 = ReadAbstractOption<Expression>();
            var parameter5 = ReadAttributesOption();
            var parameter1 = ReadBoolean();
            return new SetComprehension(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5);
        }

        public SetComprehension ReadSetComprehensionOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadSetComprehension();
        }

        public ForallExpr ReadForallExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadList<BoundVar>(() => ReadBoundVar());
            var parameter2 = ReadAbstractOption<Expression>();
            var parameter3 = ReadAbstract<Expression>();
            var parameter4 = ReadAttributesOption();
            return new ForallExpr(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public ForallExpr ReadForallExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadForallExpr();
        }

        public ExistsExpr ReadExistsExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadList<BoundVar>(() => ReadBoundVar());
            var parameter2 = ReadAbstractOption<Expression>();
            var parameter3 = ReadAbstract<Expression>();
            var parameter4 = ReadAttributesOption();
            return new ExistsExpr(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public ExistsExpr ReadExistsExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadExistsExpr();
        }

        public MapComprehension ReadMapComprehension()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter2 = ReadList<BoundVar>(() => ReadBoundVar());
            var parameter3 = ReadAbstract<Expression>();
            var parameter5 = ReadAbstract<Expression>();
            var parameter6 = ReadAttributesOption();
            var parameter1 = ReadBoolean();
            var parameter4 = ReadAbstractOption<Expression>();
            return new MapComprehension(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6);
        }

        public MapComprehension ReadMapComprehensionOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadMapComprehension();
        }

        public LambdaExpr ReadLambdaExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadList<BoundVar>(() => ReadBoundVar());
            var parameter2 = ReadAbstractOption<Expression>();
            var parameter4 = ReadAbstract<Expression>();
            var parameter5 = ReadAttributesOption();
            var parameter3 = ReadSpecification<FrameExpression>();
            return new LambdaExpr(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5);
        }

        public LambdaExpr ReadLambdaExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadLambdaExpr();
        }

        public SeqUpdateExpr ReadSeqUpdateExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            var parameter2 = ReadAbstract<Expression>();
            var parameter3 = ReadAbstract<Expression>();
            return new SeqUpdateExpr(parameter0, parameter1, parameter2, parameter3);
        }

        public SeqUpdateExpr ReadSeqUpdateExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadSeqUpdateExpr();
        }

        public SeqConstructionExpr ReadSeqConstructionExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstractOption<Type>();
            var parameter2 = ReadAbstract<Expression>();
            var parameter3 = ReadAbstract<Expression>();
            return new SeqConstructionExpr(parameter0, parameter1, parameter2, parameter3);
        }

        public SeqConstructionExpr ReadSeqConstructionExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadSeqConstructionExpr();
        }

        public MultiSetFormingExpr ReadMultiSetFormingExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            return new MultiSetFormingExpr(parameter0, parameter1);
        }

        public MultiSetFormingExpr ReadMultiSetFormingExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadMultiSetFormingExpr();
        }

        public MapDisplayExpr ReadMapDisplayExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadBoolean();
            var parameter2 = ReadList<MapDisplayEntry>(() => ReadMapDisplayEntry());
            return new MapDisplayExpr(parameter0, parameter1, parameter2);
        }

        public MapDisplayExpr ReadMapDisplayExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadMapDisplayExpr();
        }

        public MapDisplayEntry ReadMapDisplayEntry()
        {
            var parameter0 = ReadAbstract<Expression>();
            var parameter1 = ReadAbstract<Expression>();
            return new MapDisplayEntry(parameter0, parameter1);
        }

        public MapDisplayEntry ReadMapDisplayEntryOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadMapDisplayEntry();
        }

        public SetDisplayExpr ReadSetDisplayExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter2 = ReadList<Expression>(() => ReadAbstract<Expression>());
            var parameter1 = ReadBoolean();
            return new SetDisplayExpr(parameter0, parameter1, parameter2);
        }

        public SetDisplayExpr ReadSetDisplayExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadSetDisplayExpr();
        }

        public SeqDisplayExpr ReadSeqDisplayExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadList<Expression>(() => ReadAbstract<Expression>());
            return new SeqDisplayExpr(parameter0, parameter1);
        }

        public SeqDisplayExpr ReadSeqDisplayExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadSeqDisplayExpr();
        }

        public MultiSetDisplayExpr ReadMultiSetDisplayExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadList<Expression>(() => ReadAbstract<Expression>());
            return new MultiSetDisplayExpr(parameter0, parameter1);
        }

        public MultiSetDisplayExpr ReadMultiSetDisplayExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadMultiSetDisplayExpr();
        }

        public ThisExpr ReadThisExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            return new ThisExpr(parameter0);
        }

        public ThisExpr ReadThisExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadThisExpr();
        }

        public SeqSelectExpr ReadSeqSelectExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadBoolean();
            var parameter2 = ReadAbstract<Expression>();
            var parameter3 = ReadAbstractOption<Expression>();
            var parameter4 = ReadAbstractOption<Expression>();
            var parameter5 = ReadTokenOption();
            return new SeqSelectExpr(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5);
        }

        public SeqSelectExpr ReadSeqSelectExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadSeqSelectExpr();
        }

        public MultiSelectExpr ReadMultiSelectExpr()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadAbstract<Expression>();
            var parameter2 = ReadList<Expression>(() => ReadAbstract<Expression>());
            return new MultiSelectExpr(parameter0, parameter1, parameter2);
        }

        public MultiSelectExpr ReadMultiSelectExprOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadMultiSelectExpr();
        }

        public BitvectorType ReadBitvectorType()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadInt32();
            return new BitvectorType(parameter0, parameter1);
        }

        public BitvectorType ReadBitvectorTypeOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadBitvectorType();
        }

        public BigOrdinalType ReadBigOrdinalType()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            return new BigOrdinalType(parameter0);
        }

        public BigOrdinalType ReadBigOrdinalTypeOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadBigOrdinalType();
        }

        public RealType ReadRealType()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            return new RealType(parameter0);
        }

        public RealType ReadRealTypeOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadRealType();
        }

        public IntType ReadIntType()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            return new IntType(parameter0);
        }

        public IntType ReadIntTypeOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadIntType();
        }

        public CharType ReadCharType()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            return new CharType(parameter0);
        }

        public CharType ReadCharTypeOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadCharType();
        }

        public BoolType ReadBoolType()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            return new BoolType(parameter0);
        }

        public BoolType ReadBoolTypeOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadBoolType();
        }

        public SetType ReadSetType()
        {
            var parameter0 = ReadAbstractOption<IOrigin>();
            var parameter2 = ReadList<Type>(() => ReadAbstractOption<Type>());
            var parameter1 = ReadBoolean();
            return new SetType(parameter0, parameter1, parameter2);
        }

        public SetType ReadSetTypeOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadSetType();
        }

        public SeqType ReadSeqType()
        {
            var parameter0 = ReadAbstractOption<IOrigin>();
            var parameter1 = ReadList<Type>(() => ReadAbstractOption<Type>());
            return new SeqType(parameter0, parameter1);
        }

        public SeqType ReadSeqTypeOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadSeqType();
        }

        public MultiSetType ReadMultiSetType()
        {
            var parameter0 = ReadAbstractOption<IOrigin>();
            var parameter1 = ReadList<Type>(() => ReadAbstractOption<Type>());
            return new MultiSetType(parameter0, parameter1);
        }

        public MultiSetType ReadMultiSetTypeOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadMultiSetType();
        }

        public MapType ReadMapType()
        {
            var parameter0 = ReadAbstractOption<IOrigin>();
            var parameter2 = ReadList<Type>(() => ReadAbstractOption<Type>());
            var parameter1 = ReadBoolean();
            return new MapType(parameter0, parameter1, parameter2);
        }

        public MapType ReadMapTypeOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadMapType();
        }

        public TypeParameter ReadTypeParameter()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter5 = ReadAttributesOption();
            var parameter2 = ReadTPVarianceSyntax();
            var parameter3 = ReadTypeParameterCharacteristics();
            var parameter4 = ReadList<Type>(() => ReadAbstract<Type>());
            return new TypeParameter(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5);
        }

        public TypeParameter ReadTypeParameterOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadTypeParameter();
        }

        public TypeParameterCharacteristics ReadTypeParameterCharacteristics()
        {
            var parameter0 = ReadTypeParameterEqualitySupportValue();
            var parameter1 = ReadTypeAutoInitInfo();
            var parameter2 = ReadBoolean();
            return new TypeParameterCharacteristics(parameter0, parameter1, parameter2);
        }

        public TypeParameterCharacteristics ReadTypeParameterCharacteristicsOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadTypeParameterCharacteristics();
        }

        private Type.AutoInitInfo ReadTypeAutoInitInfo()
        {
            int ordinal = ReadInt32();
            return (Type.AutoInitInfo)ordinal;
        }

        private TypeParameter.EqualitySupportValue ReadTypeParameterEqualitySupportValue()
        {
            int ordinal = ReadInt32();
            return (TypeParameter.EqualitySupportValue)ordinal;
        }

        private TPVarianceSyntax ReadTPVarianceSyntax()
        {
            int ordinal = ReadInt32();
            return (TPVarianceSyntax)ordinal;
        }

        public SubsetTypeDecl ReadSubsetTypeDecl()
        {
            Microsoft.Dafny.ModuleDefinition parameter4 = null;
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter9 = ReadAttributesOption();
            var parameter3 = ReadList<TypeParameter>(() => ReadTypeParameter());
            var parameter2 = ReadTypeParameterCharacteristics();
            var parameter5 = ReadBoundVar();
            var parameter6 = ReadAbstract<Expression>();
            var parameter7 = ReadSubsetTypeDeclWKind();
            var parameter8 = ReadAbstractOption<Expression>();
            return new SubsetTypeDecl(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, parameter7, parameter8, parameter9);
        }

        public SubsetTypeDecl ReadSubsetTypeDeclOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadSubsetTypeDecl();
        }

        private SubsetTypeDecl.WKind ReadSubsetTypeDeclWKind()
        {
            int ordinal = ReadInt32();
            return (SubsetTypeDecl.WKind)ordinal;
        }

        public Method ReadMethod()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter2 = ReadAttributesOption();
            var parameter4 = ReadBoolean();
            var parameter14 = ReadAbstractOption<IOrigin>();
            var parameter5 = ReadList<TypeParameter>(() => ReadTypeParameter());
            var parameter6 = ReadList<Formal>(() => ReadFormal());
            var parameter7 = ReadList<AttributedExpression>(() => ReadAttributedExpression());
            var parameter8 = ReadList<AttributedExpression>(() => ReadAttributedExpression());
            var parameter9 = ReadSpecification<FrameExpression>();
            var parameter10 = ReadSpecification<Expression>();
            var parameter12 = ReadSpecification<FrameExpression>();
            var parameter3 = ReadBoolean();
            var parameter11 = ReadList<Formal>(() => ReadFormal());
            var parameter13 = ReadBlockStmtOption();
            var parameter15 = ReadBoolean();
            return new Method(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, parameter7, parameter8, parameter9, parameter10, parameter11, parameter12, parameter13, parameter14, parameter15);
        }

        public Method ReadMethodOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadMethod();
        }

        public Constructor ReadConstructor()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter11 = ReadAttributesOption();
            var parameter2 = ReadBoolean();
            var parameter12 = ReadAbstractOption<IOrigin>();
            var parameter3 = ReadList<TypeParameter>(() => ReadTypeParameter());
            var parameter4 = ReadList<Formal>(() => ReadFormal());
            var parameter5 = ReadList<AttributedExpression>(() => ReadAttributedExpression());
            var parameter8 = ReadList<AttributedExpression>(() => ReadAttributedExpression());
            var parameter6 = ReadSpecification<FrameExpression>();
            var parameter9 = ReadSpecification<Expression>();
            var parameter7 = ReadSpecification<FrameExpression>();
            var parameter10 = ReadDividedBlockStmtOption();
            return new Constructor(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, parameter7, parameter8, parameter9, parameter10, parameter11, parameter12);
        }

        public Constructor ReadConstructorOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadConstructor();
        }

        public Function ReadFunction()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter16 = ReadAttributesOption();
            var parameter3 = ReadBoolean();
            var parameter17 = ReadAbstractOption<IOrigin>();
            var parameter5 = ReadList<TypeParameter>(() => ReadTypeParameter());
            var parameter6 = ReadList<Formal>(() => ReadFormal());
            var parameter9 = ReadList<AttributedExpression>(() => ReadAttributedExpression());
            var parameter11 = ReadList<AttributedExpression>(() => ReadAttributedExpression());
            var parameter10 = ReadSpecification<FrameExpression>();
            var parameter12 = ReadSpecification<Expression>();
            var parameter2 = ReadBoolean();
            var parameter4 = ReadBoolean();
            var parameter7 = ReadFormalOption();
            var parameter8 = ReadAbstract<Type>();
            var parameter13 = ReadAbstractOption<Expression>();
            var parameter14 = ReadAbstractOption<IOrigin>();
            var parameter15 = ReadBlockStmtOption();
            return new Function(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, parameter7, parameter8, parameter9, parameter10, parameter11, parameter12, parameter13, parameter14, parameter15, parameter16, parameter17);
        }

        public Function ReadFunctionOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadFunction();
        }

        public Field ReadField()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter4 = ReadAttributesOption();
            var parameter2 = ReadBoolean();
            var parameter3 = ReadAbstractOption<Type>();
            return new Field(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public Field ReadFieldOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadField();
        }

        public ConstantField ReadConstantField()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter7 = ReadAttributesOption();
            var parameter4 = ReadBoolean();
            var parameter6 = ReadAbstractOption<Type>();
            var parameter2 = ReadAbstractOption<Expression>();
            var parameter3 = ReadBoolean();
            var parameter5 = ReadBoolean();
            return new ConstantField(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, parameter7);
        }

        public ConstantField ReadConstantFieldOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadConstantField();
        }

        public DatatypeCtor ReadDatatypeCtor()
        {
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter4 = ReadAttributesOption();
            var parameter2 = ReadBoolean();
            var parameter3 = ReadList<Formal>(() => ReadFormal());
            return new DatatypeCtor(parameter0, parameter1, parameter2, parameter3, parameter4);
        }

        public DatatypeCtor ReadDatatypeCtorOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadDatatypeCtor();
        }

        public IndDatatypeDecl ReadIndDatatypeDecl()
        {
            Microsoft.Dafny.ModuleDefinition parameter2 = null;
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter7 = ReadAttributesOption();
            var parameter3 = ReadList<TypeParameter>(() => ReadTypeParameter());
            var parameter6 = ReadList<MemberDecl>(() => ReadAbstract<MemberDecl>());
            var parameter5 = ReadList<Type>(() => ReadAbstract<Type>());
            var parameter4 = ReadList<DatatypeCtor>(() => ReadDatatypeCtor());
            var parameter8 = ReadBoolean();
            return new IndDatatypeDecl(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, parameter7, parameter8);
        }

        public IndDatatypeDecl ReadIndDatatypeDeclOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadIndDatatypeDecl();
        }

        public TraitDecl ReadTraitDecl()
        {
            Microsoft.Dafny.ModuleDefinition parameter2 = null;
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter5 = ReadAttributesOption();
            var parameter3 = ReadList<TypeParameter>(() => ReadTypeParameter());
            var parameter4 = ReadList<MemberDecl>(() => ReadAbstract<MemberDecl>());
            var parameter7 = ReadList<Type>(() => ReadAbstract<Type>());
            var parameter6 = ReadBoolean();
            return new TraitDecl(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, parameter7);
        }

        public TraitDecl ReadTraitDeclOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadTraitDecl();
        }

        public ClassDecl ReadClassDecl()
        {
            Microsoft.Dafny.ModuleDefinition parameter4 = null;
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter2 = ReadAttributesOption();
            var parameter3 = ReadList<TypeParameter>(() => ReadTypeParameter());
            var parameter5 = ReadList<MemberDecl>(() => ReadAbstract<MemberDecl>());
            var parameter6 = ReadList<Type>(() => ReadAbstract<Type>());
            var parameter7 = ReadBoolean();
            return new ClassDecl(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, parameter7);
        }

        public ClassDecl ReadClassDeclOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadClassDecl();
        }

        public DefaultClassDecl ReadDefaultClassDecl()
        {
            Microsoft.Dafny.ModuleDefinition parameter4 = null;
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter2 = ReadAttributesOption();
            var parameter3 = ReadList<TypeParameter>(() => ReadTypeParameter());
            var parameter5 = ReadList<MemberDecl>(() => ReadAbstract<MemberDecl>());
            var parameter6 = ReadListOption<Type>(() => ReadAbstract<Type>());
            return new DefaultClassDecl(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6);
        }

        public DefaultClassDecl ReadDefaultClassDeclOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadDefaultClassDecl();
        }

        public LiteralModuleDecl ReadLiteralModuleDecl()
        {
            Microsoft.Dafny.DafnyOptions parameter0 = null;
            Microsoft.Dafny.ModuleDefinition parameter4 = null;
            var parameter1 = ReadAbstract<IOrigin>();
            var parameter2 = ReadName();
            var parameter3 = ReadAttributesOption();
            var parameter5 = ReadString();
            var parameter6 = ReadModuleDefinition();
            return new LiteralModuleDecl(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6);
        }

        public LiteralModuleDecl ReadLiteralModuleDeclOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadLiteralModuleDecl();
        }

        public ModuleDefinition ReadModuleDefinition()
        {
            Microsoft.Dafny.ModuleDefinition parameter5 = null;
            var parameter0 = ReadAbstract<IOrigin>();
            var parameter1 = ReadName();
            var parameter2 = ReadList<IOrigin>(() => ReadAbstract<IOrigin>());
            var parameter3 = ReadModuleKindEnum();
            var parameter4 = ReadImplementsOption();
            var parameter6 = ReadAttributesOption();
            var parameter7 = ReadList<TopLevelDecl>(() => ReadAbstract<TopLevelDecl>());
            return new ModuleDefinition(parameter0, parameter1, parameter2, parameter3, parameter4, parameter5, parameter6, parameter7);
        }

        public ModuleDefinition ReadModuleDefinitionOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadModuleDefinition();
        }

        public Implements ReadImplements()
        {
            var parameter0 = ReadImplementationKind();
            var parameter1 = ReadModuleQualifiedId();
            return new Implements(parameter0, parameter1);
        }

        public Implements ReadImplementsOption()
        {
            if (ReadIsNull())
            {
                return default;
            }

            return ReadImplements();
        }

        private ImplementationKind ReadImplementationKind()
        {
            int ordinal = ReadInt32();
            return (ImplementationKind)ordinal;
        }

        private ModuleKindEnum ReadModuleKindEnum()
        {
            int ordinal = ReadInt32();
            return (ModuleKindEnum)ordinal;
        }

        private object ReadObject(System.Type actualType)
        {
            if (actualType == typeof(TokenRangeOrigin))
            {
                return ReadTokenRangeOrigin();
            }

            if (actualType == typeof(SourceOrigin))
            {
                return ReadSourceOrigin();
            }

            if (actualType == typeof(TokenRange))
            {
                return ReadTokenRange();
            }

            if (actualType == typeof(UserDefinedType))
            {
                return ReadUserDefinedType();
            }

            if (actualType == typeof(LetExpr))
            {
                return ReadLetExpr();
            }

            if (actualType == typeof(Attributes))
            {
                return ReadAttributes();
            }

            if (actualType == typeof(IdentifierExpr))
            {
                return ReadIdentifierExpr();
            }

            if (actualType == typeof(AutoGhostIdentifierExpr))
            {
                return ReadAutoGhostIdentifierExpr();
            }

            if (actualType == typeof(ConversionExpr))
            {
                return ReadConversionExpr();
            }

            if (actualType == typeof(UnaryOpExpr))
            {
                return ReadUnaryOpExpr();
            }

            if (actualType == typeof(FreshExpr))
            {
                return ReadFreshExpr();
            }

            if (actualType == typeof(BinaryExpr))
            {
                return ReadBinaryExpr();
            }

            if (actualType == typeof(LiteralExpr))
            {
                return ReadLiteralExpr();
            }

            if (actualType == typeof(StringLiteralExpr))
            {
                return ReadStringLiteralExpr();
            }

            if (actualType == typeof(CharLiteralExpr))
            {
                return ReadCharLiteralExpr();
            }

            if (actualType == typeof(UnchangedExpr))
            {
                return ReadUnchangedExpr();
            }

            if (actualType == typeof(FrameExpression))
            {
                return ReadFrameExpression();
            }

            if (actualType == typeof(OldExpr))
            {
                return ReadOldExpr();
            }

            if (actualType == typeof(DatatypeValue))
            {
                return ReadDatatypeValue();
            }

            if (actualType == typeof(ModuleQualifiedId))
            {
                return ReadModuleQualifiedId();
            }

            if (actualType == typeof(Name))
            {
                return ReadName();
            }

            if (actualType == typeof(ActualBinding))
            {
                return ReadActualBinding();
            }

            if (actualType == typeof(ActualBindings))
            {
                return ReadActualBindings();
            }

            if (actualType == typeof(TernaryExpr))
            {
                return ReadTernaryExpr();
            }

            if (actualType == typeof(NestedMatchExpr))
            {
                return ReadNestedMatchExpr();
            }

            if (actualType == typeof(LitPattern))
            {
                return ReadLitPattern();
            }

            if (actualType == typeof(IdPattern))
            {
                return ReadIdPattern();
            }

            if (actualType == typeof(DisjunctivePattern))
            {
                return ReadDisjunctivePattern();
            }

            if (actualType == typeof(NestedMatchCaseStmt))
            {
                return ReadNestedMatchCaseStmt();
            }

            if (actualType == typeof(ExpectStmt))
            {
                return ReadExpectStmt();
            }

            if (actualType == typeof(AssertStmt))
            {
                return ReadAssertStmt();
            }

            if (actualType == typeof(Label))
            {
                return ReadLabel();
            }

            if (actualType == typeof(AssertLabel))
            {
                return ReadAssertLabel();
            }

            if (actualType == typeof(AllocateClass))
            {
                return ReadAllocateClass();
            }

            if (actualType == typeof(AllocateArray))
            {
                return ReadAllocateArray();
            }

            if (actualType == typeof(ExprRhs))
            {
                return ReadExprRhs();
            }

            if (actualType == typeof(ReturnStmt))
            {
                return ReadReturnStmt();
            }

            if (actualType == typeof(PrintStmt))
            {
                return ReadPrintStmt();
            }

            if (actualType == typeof(LabeledStatement))
            {
                return ReadLabeledStatement();
            }

            if (actualType == typeof(AttributedExpression))
            {
                return ReadAttributedExpression();
            }

            if (actualType == typeof(DividedBlockStmt))
            {
                return ReadDividedBlockStmt();
            }

            if (actualType == typeof(BlockStmt))
            {
                return ReadBlockStmt();
            }

            if (actualType == typeof(OpaqueBlock))
            {
                return ReadOpaqueBlock();
            }

            if (actualType == typeof(WhileStmt))
            {
                return ReadWhileStmt();
            }

            if (actualType == typeof(IfStmt))
            {
                return ReadIfStmt();
            }

            if (actualType == typeof(BreakOrContinueStmt))
            {
                return ReadBreakOrContinueStmt();
            }

            if (actualType == typeof(VarDeclStmt))
            {
                return ReadVarDeclStmt();
            }

            if (actualType == typeof(AssignStatement))
            {
                return ReadAssignStatement();
            }

            if (actualType == typeof(LocalVariable))
            {
                return ReadLocalVariable();
            }

            if (actualType == typeof(NestedMatchStmt))
            {
                return ReadNestedMatchStmt();
            }

            if (actualType == typeof(NestedMatchCaseExpr))
            {
                return ReadNestedMatchCaseExpr();
            }

            if (actualType == typeof(ITEExpr))
            {
                return ReadITEExpr();
            }

            if (actualType == typeof(LetOrFailExpr))
            {
                return ReadLetOrFailExpr();
            }

            if (actualType == typeof(Formal))
            {
                return ReadFormal();
            }

            if (actualType == typeof(BoundVar))
            {
                return ReadBoundVar();
            }

            if (actualType == typeof(QuantifiedVar))
            {
                return ReadQuantifiedVar();
            }

            if (actualType == typeof(ParensExpression))
            {
                return ReadParensExpression();
            }

            if (actualType == typeof(ChainingExpression))
            {
                return ReadChainingExpression();
            }

            if (actualType == typeof(NegationExpression))
            {
                return ReadNegationExpression();
            }

            if (actualType == typeof(ExprDotName))
            {
                return ReadExprDotName();
            }

            if (actualType == typeof(ApplySuffix))
            {
                return ReadApplySuffix();
            }

            if (actualType == typeof(NameSegment))
            {
                return ReadNameSegment();
            }

            if (actualType == typeof(SetComprehension))
            {
                return ReadSetComprehension();
            }

            if (actualType == typeof(ForallExpr))
            {
                return ReadForallExpr();
            }

            if (actualType == typeof(ExistsExpr))
            {
                return ReadExistsExpr();
            }

            if (actualType == typeof(MapComprehension))
            {
                return ReadMapComprehension();
            }

            if (actualType == typeof(LambdaExpr))
            {
                return ReadLambdaExpr();
            }

            if (actualType == typeof(SeqUpdateExpr))
            {
                return ReadSeqUpdateExpr();
            }

            if (actualType == typeof(SeqConstructionExpr))
            {
                return ReadSeqConstructionExpr();
            }

            if (actualType == typeof(MultiSetFormingExpr))
            {
                return ReadMultiSetFormingExpr();
            }

            if (actualType == typeof(MapDisplayExpr))
            {
                return ReadMapDisplayExpr();
            }

            if (actualType == typeof(MapDisplayEntry))
            {
                return ReadMapDisplayEntry();
            }

            if (actualType == typeof(SetDisplayExpr))
            {
                return ReadSetDisplayExpr();
            }

            if (actualType == typeof(SeqDisplayExpr))
            {
                return ReadSeqDisplayExpr();
            }

            if (actualType == typeof(MultiSetDisplayExpr))
            {
                return ReadMultiSetDisplayExpr();
            }

            if (actualType == typeof(ThisExpr))
            {
                return ReadThisExpr();
            }

            if (actualType == typeof(SeqSelectExpr))
            {
                return ReadSeqSelectExpr();
            }

            if (actualType == typeof(MultiSelectExpr))
            {
                return ReadMultiSelectExpr();
            }

            if (actualType == typeof(BitvectorType))
            {
                return ReadBitvectorType();
            }

            if (actualType == typeof(BigOrdinalType))
            {
                return ReadBigOrdinalType();
            }

            if (actualType == typeof(RealType))
            {
                return ReadRealType();
            }

            if (actualType == typeof(IntType))
            {
                return ReadIntType();
            }

            if (actualType == typeof(CharType))
            {
                return ReadCharType();
            }

            if (actualType == typeof(BoolType))
            {
                return ReadBoolType();
            }

            if (actualType == typeof(SetType))
            {
                return ReadSetType();
            }

            if (actualType == typeof(SeqType))
            {
                return ReadSeqType();
            }

            if (actualType == typeof(MultiSetType))
            {
                return ReadMultiSetType();
            }

            if (actualType == typeof(MapType))
            {
                return ReadMapType();
            }

            if (actualType == typeof(TypeParameter))
            {
                return ReadTypeParameter();
            }

            if (actualType == typeof(TypeParameterCharacteristics))
            {
                return ReadTypeParameterCharacteristics();
            }

            if (actualType == typeof(SubsetTypeDecl))
            {
                return ReadSubsetTypeDecl();
            }

            if (actualType == typeof(Method))
            {
                return ReadMethod();
            }

            if (actualType == typeof(Constructor))
            {
                return ReadConstructor();
            }

            if (actualType == typeof(Function))
            {
                return ReadFunction();
            }

            if (actualType == typeof(Field))
            {
                return ReadField();
            }

            if (actualType == typeof(ConstantField))
            {
                return ReadConstantField();
            }

            if (actualType == typeof(DatatypeCtor))
            {
                return ReadDatatypeCtor();
            }

            if (actualType == typeof(IndDatatypeDecl))
            {
                return ReadIndDatatypeDecl();
            }

            if (actualType == typeof(TraitDecl))
            {
                return ReadTraitDecl();
            }

            if (actualType == typeof(ClassDecl))
            {
                return ReadClassDecl();
            }

            if (actualType == typeof(DefaultClassDecl))
            {
                return ReadDefaultClassDecl();
            }

            if (actualType == typeof(LiteralModuleDecl))
            {
                return ReadLiteralModuleDecl();
            }

            if (actualType == typeof(ModuleDefinition))
            {
                return ReadModuleDefinition();
            }

            if (actualType == typeof(Implements))
            {
                return ReadImplements();
            }

            throw new Exception($"Cannot read object of type {actualType.FullName}");
        }
    }
}