[package]
name = "minimal_fileio_test"
version = "0.1.0"
edition = "2021"

[dependencies]
dafny_runtime = { path = "runtime" }

[[bin]]
name = "minimal_fileio_test"
path = "src/minimal_fileio_test.rs"

