doo_file_version = "1.0"
dafny_version = "4.10.1.0"
[options]
allow-axioms = false
allow-deprecation = false
allow-external-contracts = false
allow-warnings = false
dont-verify-dependencies = false
enforce-determinism = true
hidden-no-verify = false
no-verify = true
reads-clauses-on-methods = true
referrers = false
relax-definite-assignment = false
standard-libraries = false
track-print-effects = true
unicode-char = true
warn-shadowing = false
analyze-proofs = false
default-function-opacity = "Transparent"
disable-nonlinear-arithmetic = false
function-syntax = "4"
manual-lemma-induction = false
manual-triggers = false
quantifier-syntax = "4"
suggest-proof-refactoring = false
warn-contradictory-assumptions = false
warn-missing-constructor-parentheses = false
warn-redundant-assumptions = false
