[package]
name = "test_custom_fileio_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
dafny_runtime = { path = "runtime" }

[[bin]]
name = "test_custom_fileio_rust"
path = "src/test_custom_fileio_rust.rs"

