#! /bin/bash -f 

## pandoc does not process the include directive in GitHub markdown
## so we do a bit of (inefficient) text processing to assemble the files
## NOTE: this script is finickhy about the white space in the include directive
## NOTE: All included files must be in the _includes folder

tmp=/tmp/t$pid
cat $@ > /tmp/t

grep -q '{% include' $tmp 
a=$?

for (( ; $a==0 ; ))
do

line=`grep -n '{% include' $tmp | head -1 | sed -e 's/:.*//'`
file=`grep -n '{% include' $tmp | head -1 | sed -e 's/.*include //' -e 's/%}//' `
la=`wc -l < $tmp`
let "ln = $line - 1"
let "lp = $la - $line"
#echo $line $file $la $ln $lp ../_includes/$file `wc -l $tmp`
head -n $ln < $tmp > /tmp/a$pid
tail -n $lp < $tmp > /tmp/b$pid
cat /tmp/a$pid ../_includes/$file /tmp/b$pid > $tmp

grep -q '{% include' $tmp
a=$?

done

mv /tmp/t DafnyRefZ.md
rm -f /tmp/a$pid /tmp/b$pid

