#! /bin/bash -f 

## pandoc does not process the include directive in GitHub markdown
## so we do a bit of (inefficient) text processing to assemble the files
## NOTE: this script is finickhy about the white space in the include directive
## NOTE: All included files must be in the _includes folder

cat $@ > /tmp/t

grep -q '{% include' /tmp/t 
a=$?

for (( ; $a==0 ; ))
do

line=`grep -n '{% include' /tmp/t | head -1 | sed -e 's/:.*//'`
file=`grep -n '{% include' /tmp/t | head -1 | sed -e 's/.*include //' -e 's/%}//' `
let "ln = $line - 1"
let "lp = $line + 1"
#echo $line $file $ln $lp ../_includes/$file
head -$ln < /tmp/t > /tmp/a
tail +$lp < /tmp/t > /tmp/b
cat /tmp/a ../_includes/$file /tmp/b > /tmp/t

grep -q '{% include' /tmp/t 
a=$?

done

mv /tmp/t DafnyRefZ.md

