//-----------------------------------------------------------------------------
//
// Copyright (C) Microsoft Corporation.  All Rights Reserved.
// Copyright by the contributors to the Dafny Project
// SPDX-License-Identifier: MIT
//
//-----------------------------------------------------------------------------
using System.Collections.Generic;
using System.Linq;
using System.Reactive;

namespace Microsoft.Dafny {

  public class UselessOldLinter : IRewriter {
    private DafnyOptions options;
    
    internal override void PostResolveIntermediate(ModuleDefinition moduleDefinition) {
      base.PostResolveIntermediate(moduleDefinition);
      foreach (var topLevelDecl in moduleDefinition.TopLevelDecls.OfType<TopLevelDeclWithMembers>()) {
        foreach (var callable in topLevelDecl.Members.OfType<ICallable>()) {
          var visitor = new UselessOldLinterVisitor(Reporter, options);
          visitor.Visit(callable, Unit.Default);
        }
      }
    }

    public UselessOldLinter(ErrorReporter reporter, DafnyOptions options) : base(reporter) {
      this.options = options;
    }
  }

  class UselessOldLinterVisitor : TopDownVisitor<Unit> {
    private DafnyOptions options;
    private readonly ErrorReporter reporter;

    public UselessOldLinterVisitor(ErrorReporter reporter, DafnyOptions options) {
      this.reporter = reporter;
      this.options = options;
    }

    protected override bool VisitOneExpr(Expression expr, ref Unit st) {
      if (expr is OldExpr oldExpr && !AutoGeneratedToken.Is(oldExpr.tok)) {
        var fvs = new HashSet<IVariable>();
        var usesHeap = false;
        FreeVariablesUtil.ComputeFreeVariables(options, oldExpr.E, fvs, ref usesHeap, true);
        if (!usesHeap) {
          oldExpr.Useless = true;
          this.reporter.Warning(MessageSource.Rewriter, ErrorDetail.ErrorID.None, oldExpr.tok,
            $"Argument to 'old' does not dereference the mutable heap, so this use of 'old' has no effect");
        }
      }
      return base.VisitOneExpr(expr, ref st);
    }
  }
}
