excludes = [
  "**/nondeterministic/*.dfy",
  "**/TargetSpecific/*.dfy",
  "**/Actions/*.dfy"
]

[options]
standard-libraries = true
reads-clauses-on-methods = true
enforce-determinism = true
resource-limit = 1000000
type-system-refresh = true
general-traits = "datatype"
general-newtypes = true
warn-redundant-assumptions = false
warn-contradictory-assumptions = true
