// RUN: ! %run --target cs --skip-included-files --allow-deprecation --unicode-char false "%s" > "%t"
// RUN: ! %run --target go --skip-included-files --allow-deprecation --unicode-char false "%s" >> "%t"
// RUN: ! %run --target java --skip-included-files --allow-deprecation --unicode-char false "%s" >> "%t"
// RUN: ! %run --target js --skip-included-files --allow-deprecation --unicode-char false "%s" >> "%t"
// RUN: ! %run --target py --skip-included-files --allow-deprecation --unicode-char false "%s" >> "%t"
// RUN: %diff "%s.expect" "%t"
include "../../expectations/ExpectAndExceptions.dfy"
