#!/usr/bin/env bash

MONO=$(which mono)

# find the source directory for this script even if it's been symlinked [issue #185]
# from https://stackoverflow.com/questions/59895/
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DAFNY_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
DAFNYSERVER="$DAFNY_ROOT/DafnyServer.exe"

if [[ ! -x "$MONO" ]]; then
    echo "Error: Dafny requires Mono to run on non-Windows systems."
    exit 1
fi

if [[ ! -f "$DAFNYSERVER" ]]; then
    echo "Error: DafnyServer.exe not found at $DAFNYSERVER."
    exit 1
fi

"$MONO" "$DAFNYSERVER" "$@"
