#!/usr/bin/env bash

# find the source directory for this script even if it's been symlinked [issue #185]
# from https://stackoverflow.com/questions/59895/
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DAFNY_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
DAFNY="$DAFNY_ROOT/Dafny.exe"

if [[ ! -e "$DAFNY" ]]; then
    echo "Error: Dafny.exe not found at $DAFNY."
    exit 1
fi

MY_OS=$(uname -s)
if [ "${MY_OS:0:5}" == "MINGW" ] || [ "${MY_OS:0:6}" == "CYGWIN" ]; then
    "$DAFNY" "$@"
else
    MONO=$(which mono)
    if [[ ! -x "$MONO" ]]; then
	echo "Error: Dafny requires Mono to run on non-Windows systems."
	exit 1
    fi
    "$MONO" "$DAFNY" "$@"
fi
