#!/usr/bin/env bash

MONO=$(which mono)
DAFNY=$(dirname `readlink -f "${BASH_SOURCE[0]}"`)/Dafny.exe

if [[ ! -x "$MONO" ]]; then
    echo "Error: Dafny requires Mono to run on non-Windows systems."
    exit 1
fi

if [[ ! -e "$DAFNY" ]]; then
    echo "Error: Dafny.exe not found at $DAFNY."
    exit 1
fi

"$MONO" "$DAFNY" "$@"
