#! /usr/bin/env bash

d=$(dirname ${BASH_SOURCE[0]})
cd $d

echo ">>>> REFINEMENT"

csfiles="../../Source/DafnyCore/Resolver/RefinementTransformer.cs"
./check-errors-a Errors-Refinement.md "$csfiles" ../../Source/DafnyCore/Resolver/RefinementErrors.cs

exit 0

echo ">>>> REWRITER"

csfiles="../../Source/DafnyCore/Rewriters/*.cs ../../Source/DafnyCore/Rewriters/*/*.cs"
./check-errors-a Errors-Rewriter.md "$csfiles" ../../Source/DafnyCore/Rewriters/RewriterErrors.cs

echo ">>>> COMPILER"

csfiles="../../Source/DafnyCore/Compilers/*.cs ../../Source/DafnyCore/Compilers/*/*.cs"
./check-errors-a Errors-Compiler.md "$csfiles" ../../Source/DafnyCore/Compilers/CompilerErrors.cs

##echo ">>>> PARSER"

##./check-errors-a Errors-Parser.md ../../Source/DafnyCore/Dafny.atg ../../Source/DafnyCore/AST/Grammar/ParseErrors.cs

