#! /usr/bin/env bash
dir=$(dirname "${BASH_SOURCE[0]}")
cd "$dir"

FAIL=0
java MakeErrorCatalog.java Errors-Compiler.template \
      ../../Source/DafnyCore/Compilers/CompilerErrors.cs 
if [ "?$" != "0" ] ; then exit 1; fi

diff Errors-Compiler.tmp Errors-Compiler.md || \
   { echo "Errors-Compiler.md has been altered -- check and commit the edits"; FAIL=1; }


if [ "$FAIL" != "0" ]; then exit 1; fi


