excludes = [
  # Built per-target language instead
  "**/TargetSpecific/*.dfy",
  # Exclude ORDINAL-dependent modules for Rust compatibility
  "Ordinal.dfy",
  "Termination.dfy", 
  "Frames.dfy",
  "Actions/*.dfy",
  # Exclude JSON modules due to Rust code generation issues with Bracketed datatype
  "JSON/**/*.dfy",
  # Exclude modules with verification issues
  "Base64.dfy",
  "Arithmetic/**/*.dfy",
  # Exclude Strings since it depends on Arithmetic
  "Strings.dfy",
]

[options]
track-print-effects = true
enforce-determinism = true
reads-clauses-on-methods = true
type-system-refresh = true
general-traits = "datatype"
general-newtypes = true
resource-limit = 10000000
verification-time-limit = 1200
warn-redundant-assumptions = false
warn-contradictory-assumptions = false