excludes = [
  # Built per-target language instead
  "**/TargetSpecific/*.dfy",
  # Exclude only the most problematic modules
  "Ordinal.dfy",
  "Termination.dfy", 
  "Frames.dfy",
]

[options]
track-print-effects = true
enforce-determinism = true
reads-clauses-on-methods = true
type-system-refresh = true
general-traits = "datatype"
general-newtypes = true
resource-limit = 1000000
verification-time-limit = 300
warn-redundant-assumptions = false
warn-contradictory-assumptions = false
