excludes = [
  "**/nondeterministic/*.dfy",
  "**/TargetSpecific/*.dfy"
]

[options]
standard-libraries = false
enforce-determinism = true
reads-clauses-on-methods = true
type-system-refresh = true
general-traits = "datatype"
general-newtypes = true

resource-limit = 1000000
# These give too many false positives right now, but should be enabled in the future
warn-redundant-assumptions = false
warn-contradictory-assumptions = true
