// NONUNIFORM: Tests that datatype members like hash do not shadow those generated by Rust backend
// RUN: %baredafny run --target=rs --enforce-determinism "%s" > "%t"
// RUN: %diff "%s.expect" "%t"

datatype Loop = Loop(loop: Loop) | Point() {
  function hash(): string {
    "This is Dafny Hash"
  }
}

datatype Loop2 = Loop2(loop: Loop) {
  method hash() {
    print "\nThis is Dafny hash 2";
  }

  method doHash() {
    hash();
  }
}

method Main() {
  var t := Loop(Point());
  print t.hash();
  Loop2(t).hash();
}