// NONUNIFORM: Tests that datatype members like hash do not shadow those generated by Rust backend
// RUN: %baredafny run --target=rs "%s" > "%t"
// RUN: %diff "%s.expect" "%t"

datatype Loop = Loop(loop: Loop) | Point() {
  function hash(): string {
    "uh-oh!"
  }
}