
all: check-system-module

check-system-module:
	make -C DafnyRuntimeCSharp check-system-module
	make -C DafnyRuntimeJava check-system-module
	make -C DafnyRuntimeGo check-system-module
	make -C DafnyRuntimePython check-system-module
	make -C DafnyRuntimeJs check-system-module
	# make -C DafnyRuntimeRust check-system-module
	
update-system-module:
	make -C DafnyRuntimeCSharp update-system-module
	make -C DafnyRuntimeJava update-system-module
	make -C DafnyRuntimeGo update-system-module
	make -C DafnyRuntimePython update-system-module
	make -C DafnyRuntimeJs update-system-module
	# make -C DafnyRuntimeRust update-system-module
	
	