
update-system-module:
	# make -C DafnyRuntimeCSharp update-system-module
	# make -C DafnyRuntimeJava update-system-module
	make -C DafnyRuntimeGo update-system-module
	# make -C DafnyRuntimePython update-system-module
	# make -C DafnyRuntimeJs update-system-module
	# make -C DafnyRuntimeRust update-system-module
	
	