// RUN: %verify --allow-deprecation --unicode-char false --verify-included-files "%s" > "%t"
// RUN: ! %baredafny test %args --allow-deprecation --unicode-char false --no-verify --target:cs "%s" >> "%t"
// RUN: ! %baredafny test %args --allow-deprecation --unicode-char false --no-verify --target:java "%s" >> "%t"
// RUN: ! %baredafny test %args --allow-deprecation --unicode-char false --no-verify --target:go "%s" >> "%t"
// RUN: ! %baredafny test %args --allow-deprecation --unicode-char false --no-verify --target:js "%s" >> "%t"
// RUN: ! %baredafny test %args --allow-deprecation --unicode-char false --no-verify --target:py "%s" >> "%t"
// RUN: %diff "%s.expect" "%t" 
include "../../DafnyTests/RunAllTests/RunAllTestsOption.dfy"
